export const ENV_VARS = {
    REDIS_HOST: "REDIS_HOST",
    REDIS_PORT: "REDIS_PORT",
    REDIS_PASSWORD: "REDIS_PASSWORD",
    LOG_LEVEL: "LOG_LEVEL",
    REST_REQUEST_TIMEOUT: "REST_REQUEST_TIMEOUT",
    EVENT_DISCONNECTED_URL: "EVENT_DISCONNECTED_URL",
}